coverage:
  range: 80..90
  round: down
  precision: 2

comment:
  layout: diff, files

ignore:
  - "**/utils"
  - "**/commonTest"
  - "**/androidTest"
  - "**/iOSTest"
  - "**/jsTest"
  - "**/jvmTest"